### ISSUE TITLE
I Searched For Ages Man 😢

### ISSUE THREAD

**Issue by karimawi** [Stormix/spotify-liked#1]
![image](https://user-images.githubusercontent.com/69881381/173014444-fc708f88-5293-4397-b6aa-04937131478d.png)
do you still support this project? I want to get added to the beta if you still host this project, cause the web dash "Login With Spotify" button prompts "Something Went Wrong!" error when it's clicked.

**Comment by Stormix** [comment]
@karimawii I haven't checked it in a while, but I'll see if it's still running, leave your spotify email here so I can invite you to the app.

**Comment by Stormix** [comment]
Works, send me your email 👍🏼 

![2022-06-13 19_07_34-package json - spotify-liked - Visual Studio Code](https://user-images.githubusercontent.com/18377687/173407596-602691cf-d69c-4e45-8d8c-173c8de6c151.png)

**Comment by karimawi** [comment]
karimwalid01207156734@gmail.com

**Comment by karimawi** [comment]
btw can I use an existing playlist after emptying it instead of generating a new one? Because I've shared it's link to several ppl and it has many likes

**Comment by Stormix** [comment]
It's possible, you can login to create an account and make a playlist (a new one yes)
Then dm me via [twitter ](https://twitter.com/Stormix_co) or discord (`𝕾𝖙𝖔𝖗𝖒𝖎𝖝#0001`) to send me the playlist you want to sync instead and I'll replace the IDs in the backend.
